---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Datadok key export'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Datadog key'
      Parameters:
      - DataDogKey
Parameters:
  DataDogKey:
    Description: 'DataDog Key will be exported'
    Type: String
Resources:
  Dummy:
    Type: 'AWS::S3::Bucket'
    Properties: {}
Outputs:
  DataDogKey:
    Description: 'DataDog Key will be exported'
    Value: !Ref DataDogKey
    Export:
      Name: !Sub '${AWS::StackName}-DataDogKey'
